# -*- coding: utf-8 -*-
"""MESSY.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sXw6ddag4qB6TjIKvoHPeSHBirClsk69
"""

NUM_SCORES = 3

students = [
    ["Rahul", 78, 88, 92],
    ["Priya", 65, 71, 69],
    ["Amit", 90, 94, 85],
    ["Sneha", 55, 60, 58],
    ["Vikram", 82, 79, 88]
]


def sum_scores(student):
    """Return the sum of numeric scores in a student record, skipping the name."""
    total = 0
    for index in range(1, len(student)):
        total = total + student[index]
    return total


def average_score(student):
    return sum_scores(student) / NUM_SCORES


def class_average(roster):
    total = 0
    for student in roster:
        total = total + average_score(student)
    return total / len(roster)


def count_above_class_average(roster):
    """Return how many students have an average strictly above the class average."""
    mean = class_average(roster)
    count = 0
    for student in roster:
        if average_score(student) > mean:
            count = count + 1
    return count


print("REPORT")

for student in students:
    total = sum_scores(student)
    average = average_score(student)
    name = student[0]

    if average >= 90:
        grade = "A"
    elif average >= 80:
        grade = "B"
    elif average >= 70:
        grade = "C"
    elif average >= 60:
        grade = "D"
    else:
        grade = "F"

    print(f"{name}{total}{average}{grade}")

print(f"Class average:{class_average(students)}")
print(f"Students above class average:{count_above_class_average(students)}")

highest_average = 0
topper_name = ""

for student in students:
    average = average_score(student)

    if average > highest_average:
        highest_average = average
        topper_name = student[0]

print(f"Topper:{topper_name}{highest_average}")
